version: '3'

services:
  lib_home:
    build:
      context: .
      dockerfile: Dockerfile
#    image: marolok/dark_sun:1.0.0
    env_file:
      - .env
    volumes:
      - "${PC_DB_PATH}:${DATA_PATH}"
    tty: true
    restart: always
    networks:
      - bridge
    ports:
      - '8080:8080'
networks:
  bridge:
    driver: bridge