version: '3'
name: lib-home
services:
  ui:
    image: marolok/lib_home:4.2.0
#    build:
#      context: LibHomeUI
#      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - "${PC_DB_PATH}:${DATA_PATH}"
    tty: true
    restart: always
    networks:
      - bridge
    ports:
      - '8080:8080'
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ${MONGO_DIR}:/data/db
      - ./db_init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=admin
      - MONGO_WORK_DATABASE=libhomedb
      - MONGO_WORK_USER=mrlk_u
      - MONGO_WORK_PASSWORD=mrlk_p
    networks:
      - mgdb
  db:
    image: marolok/lib_home_db:1.0.0
#    build:
#      context: LibHomeDB
#      dockerfile: Dockerfile
    env_file:
      - .env
    tty: true
    restart: always
    networks:
      - mgdb
      - bridge


networks:
  bridge:
    driver: bridge
  mgdb:
    external: false