<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.5.6</version>
        <relativePath/>
    </parent>

    <groupId>com.mar</groupId>
    <artifactId>lib-home</artifactId>
    <version>4.2.0</version>
    <packaging>pom</packaging>
    <name>lib-home</name>
    <description>LibHome - your book, game, music and other library.</description>

    <modules>
        <module>LibHomeData</module>
        <module>LibHomeDB</module>
        <module>LibHomeUI</module>
    </modules>

    <properties>
        <com.mar.libhome.dto>1.0.0</com.mar.libhome.dto>
        <com.mar.libhome.db>1.0.0</com.mar.libhome.db>

        <java.version>17</java.version>
        <vaadin.version>14.7.3</vaadin.version>

        <org.mapstruct.version>1.6.3</org.mapstruct.version>
        <org.apache.lang3.version>3.12.0</org.apache.lang3.version>
        <org.mapstruct.version>1.5.5.Final</org.mapstruct.version>
        <fastxml.version>2.19.2</fastxml.version>
    </properties>

    <repositories>
        <repository>
            <id>vaadin-addons</id>
            <url>https://maven.vaadin.com/vaadin-addons</url>
        </repository>
    </repositories>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.mar</groupId>
                <artifactId>LibHomeData</artifactId>
                <version>${com.mar.libhome.dto}</version>
            </dependency>
            <dependency>
                <groupId>com.mar</groupId>
                <artifactId>LibHomeDB</artifactId>
                <version>${com.mar.libhome.db}</version>
            </dependency>

            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct</artifactId>
                <version>${org.mapstruct.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-lang3</artifactId>
                <version>${org.apache.lang3.version}</version>
            </dependency>
<!--            <dependency>-->
<!--                <groupId>com.fasterxml.jackson.core</groupId>-->
<!--                <artifactId>jackson-databind</artifactId>-->
<!--                <version>${fastxml.version}</version>-->
<!--            </dependency>-->
        </dependencies>
    </dependencyManagement>


</project>
