server.port=8080
java.version=@java.version@
vaadin.version=@vaadin.version@

db.card.url=http://localhost:8088
spring.cloud.openfeign.client.config.default.connectTimeout=5000
spring.cloud.openfeign.client.config.default.readTimeout=5000
spring.cloud.openfeign.client.config.default.loggerLevel=full



#TODO Поменять на нормальный
application.bot.admin.login=marolok
application.bot.admin.pwd.md5=c082f033f5f0faaf34dcfff095cbe7f1

app.version=@version@
#app.data.path=/home/marolok/IdeaProjects/LibHome/test_dir/
#app.data.content.file=/home/marolok/IdeaProjects/LibHome/content.json

app.data.path=C:/Users/user/IdeaProjects/LibHome/LB/
app.data.content.file=C:/Users/user/IdeaProjects/LibHome/LibHomeUI/content.json

app.image.max.height=600
app.card.point.min=0
app.card.point.max=10
app.grid.row.count=20

spring.application.name=@artifactId@
spring.servlet.multipart.max-file-size=10MB
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.format_sql=true