spring.application.name=libhome.db
server.port=8088

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=libhomedb
spring.data.mongodb.username=mrlk_u
spring.data.mongodb.password=mrlk_p
spring.data.mongodb.auto-index-creation=true

spring.mvc.problemdetails.enabled=true