spring.application.name=libhome.db
server.port=8088
# ----------------------------------------
# Настройки подключения к PostgreSQL
# ----------------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/your_database_name
spring.datasource.username=your_username
spring.datasource.password=your_password
spring.datasource.driver-class-name=org.postgresql.Driver
# ----------------------------------------
# Настройки JPA / Hibernate
# ----------------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# ----------------------------------------
# Логирование и отладка
# ----------------------------------------
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
